language: nix
install:
  - nix-shell --quiet --command "virtualenv venv && . ./venv/bin/activate && pip install --process-dependency-links -e '.[test]'"
script:
  - nix run --quiet nixpkgs.python3Packages.mypy -c mypy hase
