language: nix
install:
  - nix-shell --command "virtualenv venv && . ./venv/bin/activate && pip install --process-dependency-links -e '.[test]' && ./bin/build-mypy-path"
script:
  - nix run nixpkgs.python3Packages.mypy -c mypy .
