language: python
python:
  - "3.6"
install:
  - pip install mypy
script:
  - mypy hase tests/benchmark
branches:
  only:
  - master

#language: nix
#script:
#  - nix run --quiet nixpkgs.python3Packages.mypy -c mypy hase
#  # too slow at the moment, needs caching
#  #  - nix-shell --quiet --command "virtualenv venv && . ./venv/bin/activate && pip install --quiet --process-dependency-links -e '.[test]'"
